---
- name: Run using a project directory
  hosts: all
  gather_facts: no
  tasks:
    - name: get source
      ansible.builtin.git:
        repo: 'https://github.com/ronaksuchak/crypto.git'
        dest: ~/src/
        
    # - name: This command will change the working directory to somedir/
    #   ansible.builtin.shell:
    #     cmd: ls -l 
    - name: Create and start services
      docker_compose:
        project_src: /home/azureuser/src
      register: output
       
    - debug:
        var: output
