- name: Run using a project directory
  hosts: all
  gather_facts: no
  tasks:
     - name: Create and start services
      docker_compose:
        project_src: .
      register: output

    - debug:
        var: output
