name: CI
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install ansible on runner
        run: |
          sudo apt update
          sudo apt install software-properties-common
          pip install python-apt
          pip install docker docker-compose
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
      - name: change permission
        run: sudo chmod 400 actions/ansible/crypto.pem
      - name: list and pwd
        run: |
          ls actions/ansible/
          pwd
#       - name: Run playbook install docker
#         uses: dawidd6/action-ansible-playbook@v2
#         with:
#           # Required, playbook filepath
#           playbook: install-docker.yml
#           # Optional, directory where playbooks live
#           directory: actions/ansible
#           # Optional, SSH private key
#           #key: ${{secrets.SSH_PRIVATE_KEY}}
#           # Optional, literal inventory file contents
#           inventory: |
#             [all:vars]
#             ansible_ssh_private_key_file=/home/runner/work/crypto/crypto/actions/ansible/crypto.pem
#             [all]
#             23.102.62.28
      - name: Run playbook for docker compose 
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy.yml
          # Optional, directory where playbooks live
          directory: actions/ansible
          # Optional, SSH private key
          #key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all:vars]
            ansible_ssh_private_key_file=/home/runner/work/crypto/crypto/actions/ansible/crypto.pem
            [all]
            23.102.62.28
